name=ESP32_SecureCrypto
version=1.0.0
author=VM Nitesh
maintainer=VM Nitesh
sentence=AES-GCM and XTEA encryption library for ESP32 over ESP-NOW and HTTPS.
paragraph=A lightweight wrapper for mbedtls AES-GCM and custom XTEA block ciphers, designed for secure IoT communication.
category=Communication
url=https://github.com/
architectures=esp32
includes=ESP32_SecureCrypto.h
